# <center>How Machine Learning Works Simply</center>
#### <center>Author : Erhan Namlı</center>

# <span style="text-align:center">Introduction</span>

Greetings, I created this document to show how you can use ML easily about any topic.

# Setup

In [56]:
import numpy as np

In [57]:
import pandas as pd

In [58]:
df = pd.DataFrame()

Let's create an original dataset, but this dataset must be sensible because of the health of our model.

## Creating a random dataset

<img src="equation.PNG">

x = 10k, y=5k, z=1k

The purpose of our model is to estimate these coefficients and then produce the appropriate result for the parameters given to it.

In [78]:
x = np.random.randint(1,101, 1250)
y = np.random.randint(1,101, 1250)
z = np.random.randint(1,101, 1250)
result=[]

In [79]:
for i in range(len(x)):
    result.append(i)

In [80]:
for i in range(len(x)-1):
    
    result[i] = x[i]*7 + y[i]*3 + z[i]*8

In [81]:
df["x"] = x
df["y"] = y
df["z"] = z
df["result"] = result

In [82]:
df

x   y   z  result
0     83  81  28    1048
1     46  83  95    1331
2     45  93  51    1002
3     37  88  70    1083
4     56  85  28     871
...   ..  ..  ..     ...
1245  80  68   7     820
1246  60  38  79    1166
1247  23  48  70     865
1248  39  53  12     528
1249  17  72  70    1249

[1250 rows x 4 columns]

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [84]:
X = df[['x', 'y', 'z']]
y = df['result']

In [85]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.1,random_state=13) #train_size=0.8

In [86]:
lr=LinearRegression()
regmodel=lr.fit(X_train, y_train)

In [87]:
from sklearn.metrics import mean_squared_error,r2_score

In [88]:
y_pretest=lr.predict(X_test)

In [89]:
r2_score(y_test,y_pretest)

0.9999968740406303

In [90]:
deneme = pd.DataFrame()

In [91]:
x = 10
y = 5
z = 1

In [92]:
deneme['x'] = [10]
deneme['y'] = [1]
deneme['z'] = [1]

In [93]:
lr.coef_

array([6.98728798, 3.00741166, 8.0067653 ])

In [94]:
lr.predict(deneme)

array([81.10231862])

# Testing on Real Life Application

Let's say there is a maze and that maze has no fork in the road, and we have a car that has 3 distance sensors. That sensors evaluate right, left, and front obstacle's distance. We can record that distances when deciding which way to turn. 

<img src="roadmap.png">

<img src="real.jpg">

This is a sensor that evaluates distance between car and obstacle

<img src="hcsr04.PNG">

In [95]:
df2 = pd.DataFrame()

In [96]:
right_sensor = np.random.randint(1,255,1500)
left_sensor = np.random.randint(1,255,1500)
front_sensor  = np.random.randint(1,255,1500)
direction=[]

In [97]:
for i in range(len(right_sensor)):
    direction.append(i)

In [98]:
for i in range(len(right_sensor)):
    
    if front_sensor[i]<100:
        
        if 3*right_sensor[i] < left_sensor[i]:
            
            direction[i] = "LEFT"
            
        elif 3*left_sensor[i] < right_sensor[i]:
            
            direction[i] = "RIGHT"
        else:
            direction[i] = "STRAIGHT"
    else:
        
        direction[i] = "STRAIGHT"

In [99]:
df2['right_sensor'] = right_sensor
df2['left_sensor'] = left_sensor
df2['front_sensor'] = front_sensor
df2['direction'] = direction

In [100]:
df2

right_sensor  left_sensor  front_sensor direction
0              213          170           134  STRAIGHT
1               98          142           150  STRAIGHT
2              245            4            14     RIGHT
3              227            1           174  STRAIGHT
4              198           34           144  STRAIGHT
...            ...          ...           ...       ...
1495           238          244            49  STRAIGHT
1496           238          155           155  STRAIGHT
1497            82           55           228  STRAIGHT
1498           244          155            77  STRAIGHT
1499           232           36            79     RIGHT

[1500 rows x 4 columns]

In [101]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [102]:
Xdf2 = df2[['right_sensor', 'left_sensor', 'front_sensor']]
ydf2 = df2['direction']

In [103]:
x_train,x_test,y_train,y_test=train_test_split(Xdf2, ydf2, random_state=80)

In [104]:
x_train

right_sensor  left_sensor  front_sensor
919             80          226            54
1227           215          195           183
992            211           56           231
48             225          152           133
735            163          196            11
...            ...          ...           ...
522            150           10           102
211            197          216            76
934             30          148            37
1212           185          242           110
1199           239          157           153

[1125 rows x 3 columns]

In [105]:
y_train

919     STRAIGHT
1227    STRAIGHT
992     STRAIGHT
48      STRAIGHT
735     STRAIGHT
          ...   
522     STRAIGHT
211     STRAIGHT
934         LEFT
1212    STRAIGHT
1199    STRAIGHT
Name: direction, Length: 1125, dtype: object

In [106]:
b=MultinomialNB()
model=b.fit(x_train, y_train)
b_predict=b.predict(x_test)

In [113]:
b.coef_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


array([[-2.13448446, -0.3934495 , -1.57518604],
       [-0.33534378, -2.20080645, -1.74758593],
       [-1.13329034, -1.09578764, -1.06783577]])

In [107]:
accuracy_score(y_test,b_predict)

0.816

In [108]:
temp = pd.DataFrame()

In [111]:
temp['right_sensor'] = [180]
temp['left_sensor'] = [10]
temp['front_sensor'] = [20]

In [112]:
b.predict(temp)

array(['RIGHT'], dtype='<U8')